#!/usr/bin/python3

import pandas

def main():

    # make a dataframe from jsond
    df = pandas.read_json("5movies.json")

    # writeout dataframe to CSV
    df.to_csv("5movies-translated-from-json.csv")

if __name__ == "__main__":
    main()
