#!/usr/bin/python3

import pandas

def main():

    # make a dataframe from json
    df = pandas.read_json("5movies.json")

    # writeout dataframe to CSV
    df.to_excel("5movies-translated-from-json.csv")

if __name__ == "__main__":
    main()
